-- Initial schema for a fresh PostgreSQL 18+ deployment.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA public;

CREATE TABLE abilities (
    "group" character varying(64) NOT NULL,
    model character varying(255) NOT NULL,
    channel_id bigint NOT NULL,
    enabled boolean,
    priority bigint DEFAULT 0,
    weight bigint DEFAULT 0,
    tag text,
    CONSTRAINT abilities_pkey PRIMARY KEY ("group", model, channel_id)
);

CREATE INDEX idx_abilities_channel_id ON abilities USING btree (channel_id);

CREATE INDEX idx_abilities_priority ON abilities USING btree (priority);

CREATE INDEX idx_abilities_tag ON abilities USING btree (tag);

CREATE INDEX idx_abilities_weight ON abilities USING btree (weight);

-- A spent provider signature remains spent after cache loss. These durable
-- receipts contain no authentication challenge or session payload.
CREATE TABLE auth_assertion_receipts (
    token_hash character(64) PRIMARY KEY,
    purpose character varying(32) NOT NULL,
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz NOT NULL
);
CREATE INDEX idx_auth_assertion_receipts_expiry ON auth_assertion_receipts (expires_at);

CREATE TABLE authz_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    key character varying(64) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    built_in boolean,
    enabled boolean,
    sort bigint,
    created_at bigint,
    updated_at bigint,
    CONSTRAINT authz_roles_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_authz_roles_key ON authz_roles USING btree (key);

CREATE TABLE casbin_rule (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ptype character varying(100),
    v0 character varying(100),
    v1 character varying(100),
    v2 character varying(100),
    v3 character varying(100),
    v4 character varying(100),
    v5 character varying(100),
    CONSTRAINT casbin_rule_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_casbin_rule ON casbin_rule USING btree (ptype, v0, v1, v2, v3, v4, v5);

CREATE UNIQUE INDEX idx_casbin_rule_unique ON casbin_rule USING btree (ptype, v0, v1, v2, v3, v4, v5);

CREATE TABLE channels (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type bigint DEFAULT 0,
    key text NOT NULL,
    open_ai_organization text,
    test_model text,
    status bigint DEFAULT 1,
    name text,
    weight bigint DEFAULT 0,
    created_time bigint,
    test_time bigint,
    response_time bigint,
    base_url text DEFAULT ''::text,
    other text,
    balance numeric,
    balance_updated_time bigint,
    models text[] NOT NULL DEFAULT '{}',
    "group" text[] NOT NULL DEFAULT '{default}',
    used_quota bigint DEFAULT 0,
    model_mapping jsonb,
    status_code_mapping jsonb,
    priority bigint DEFAULT 0,
    auto_ban bigint DEFAULT 1,
    other_info jsonb,
    tag text,
    setting jsonb,
    param_override jsonb,
    header_override jsonb,
    remark character varying(255),
    channel_info jsonb,
    settings jsonb,
    CONSTRAINT channels_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_channels_name ON channels USING gin (name public.gin_trgm_ops);

CREATE INDEX idx_channels_groups ON channels USING gin ("group");

CREATE INDEX idx_channels_tag ON channels USING btree (tag);

CREATE TABLE checkins (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint NOT NULL,
    checkin_date character varying(10) NOT NULL,
    quota_awarded bigint NOT NULL,
    created_at bigint,
    CONSTRAINT checkins_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_user_checkin_date ON checkins USING btree (user_id, checkin_date);

CREATE TABLE custom_oauth_providers (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(64) NOT NULL,
    slug character varying(64) NOT NULL,
    icon character varying(128) DEFAULT ''::character varying,
    enabled boolean DEFAULT false,
    client_id character varying(256),
    client_secret character varying(512),
    authorization_endpoint character varying(512),
    token_endpoint character varying(512),
    user_info_endpoint character varying(512),
    scopes character varying(256) DEFAULT 'openid profile email'::character varying,
    user_id_field character varying(128) DEFAULT 'sub'::character varying,
    username_field character varying(128) DEFAULT 'preferred_username'::character varying,
    display_name_field character varying(128) DEFAULT 'name'::character varying,
    email_field character varying(128) DEFAULT 'email'::character varying,
    well_known character varying(512),
    auth_style bigint DEFAULT 0,
    access_policy text,
    access_denied_message character varying(512),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    CONSTRAINT custom_oauth_providers_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_custom_oauth_providers_slug ON custom_oauth_providers USING btree (slug);

CREATE TABLE external_identity_claims (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    provider character varying(32) NOT NULL,
    subject character varying(128) NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp with time zone,
    CONSTRAINT external_identity_claims_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_external_identity_claims_user_id ON external_identity_claims USING btree (user_id);

CREATE UNIQUE INDEX idx_external_identity_subject ON external_identity_claims USING btree (provider, subject);

CREATE UNIQUE INDEX idx_external_identity_user ON external_identity_claims USING btree (provider, user_id);

CREATE TABLE login_encryption_keys (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    slot character varying(32) NOT NULL,
    private_key_pem text NOT NULL,
    CONSTRAINT login_encryption_keys_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_login_encryption_keys_slot ON login_encryption_keys USING btree (slot);

CREATE TABLE midjourneys (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code bigint,
    user_id bigint,
    action character varying(40),
    mj_id text,
    prompt text,
    prompt_en text,
    description text,
    state text,
    submit_time bigint,
    start_time bigint,
    finish_time bigint,
    image_url text,
    video_url text,
    video_urls text,
    status character varying(20),
    progress character varying(30),
    fail_reason text,
    channel_id bigint,
    quota bigint,
    billing_pending boolean NOT NULL DEFAULT false,
    billing_action character varying(32) NOT NULL DEFAULT ''::character varying,
    billing_operation_id character varying(128) NOT NULL DEFAULT ''::character varying,
    billing_target_quota bigint NOT NULL DEFAULT 0,
    billing_delta bigint NOT NULL DEFAULT 0,
    buttons text,
    properties text,
    token_id bigint DEFAULT 0,
    billing_channel_id bigint DEFAULT 0,
    billing_request_id character varying(64) NOT NULL DEFAULT ''::character varying,
    billing_token_unlimited boolean NOT NULL DEFAULT false,
    billing_playground boolean NOT NULL DEFAULT false,
    billing_free_model boolean NOT NULL DEFAULT false,
    billing_source character varying(32) NOT NULL DEFAULT 'wallet'::character varying,
    billing_subscription_id bigint NOT NULL DEFAULT 0,
    CONSTRAINT midjourneys_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_midjourneys_action ON midjourneys USING btree (action);

CREATE INDEX idx_midjourneys_finish_time ON midjourneys USING btree (finish_time);

CREATE UNIQUE INDEX idx_midjourneys_mj_id ON midjourneys USING btree (mj_id) WHERE mj_id <> '';

CREATE INDEX idx_midjourneys_billing_pending ON midjourneys USING btree (billing_pending, billing_action, id);

ALTER TABLE midjourneys ADD CONSTRAINT midjourneys_billing_action_check
    CHECK (billing_action IN ('', 'settlement', 'refund', 'unknown'));

ALTER TABLE midjourneys ADD CONSTRAINT midjourneys_billing_source_check
    CHECK (billing_source IN ('wallet', 'subscription'));

CREATE INDEX idx_midjourneys_progress ON midjourneys USING btree (progress);

CREATE INDEX idx_midjourneys_start_time ON midjourneys USING btree (start_time);

CREATE INDEX idx_midjourneys_status ON midjourneys USING btree (status);

CREATE INDEX idx_midjourneys_submit_time ON midjourneys USING btree (submit_time);

CREATE INDEX idx_midjourneys_user_id ON midjourneys USING btree (user_id);

CREATE TABLE models (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model_name character varying(128) NOT NULL,
    description text,
    icon character varying(128),
    tags character varying(255),
    vendor_id bigint,
    endpoints text,
    status bigint DEFAULT 1,
    sync_official bigint DEFAULT 1,
    created_time bigint,
    updated_time bigint,
    deleted_at timestamp with time zone,
    name_rule bigint DEFAULT 0,
    CONSTRAINT models_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_models_deleted_at ON models USING btree (deleted_at);

CREATE INDEX idx_models_vendor_id ON models USING btree (vendor_id);

CREATE UNIQUE INDEX uk_model_name_delete_at ON models USING btree (model_name, deleted_at);

CREATE TABLE options (
    key text NOT NULL,
    value text,
    CONSTRAINT options_pkey PRIMARY KEY (key)
);

CREATE TABLE passkey_credentials (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint NOT NULL,
    credential_id character varying(512) NOT NULL,
    public_key text NOT NULL,
    attestation_type character varying(255),
    aa_guid character varying(512),
    sign_count bigint DEFAULT 0,
    clone_warning boolean,
    user_present boolean,
    user_verified boolean,
    backup_eligible boolean,
    backup_state boolean,
    transports text,
    attachment character varying(32),
    last_used_at timestamp with time zone,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT passkey_credentials_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_passkey_credentials_credential_id ON passkey_credentials USING btree (credential_id);

CREATE INDEX idx_passkey_credentials_deleted_at ON passkey_credentials USING btree (deleted_at);

CREATE UNIQUE INDEX idx_passkey_credentials_user_id ON passkey_credentials USING btree (user_id);

CREATE TABLE perf_metrics (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model_name character varying(128),
    "group" character varying(64),
    bucket_ts bigint,
    request_count bigint DEFAULT 0,
    success_count bigint DEFAULT 0,
    total_latency_ms bigint DEFAULT 0,
    ttft_sum_ms bigint DEFAULT 0,
    ttft_count bigint DEFAULT 0,
    output_tokens bigint DEFAULT 0,
    generation_ms bigint DEFAULT 0,
    CONSTRAINT perf_metrics_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_perf_bucket_ts ON perf_metrics USING btree (bucket_ts);

CREATE UNIQUE INDEX idx_perf_model_group_bucket ON perf_metrics USING btree (model_name, "group", bucket_ts);

CREATE TABLE prefill_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(64) NOT NULL,
    type character varying(32) NOT NULL,
    items jsonb,
    description character varying(255),
    created_time bigint,
    updated_time bigint,
    deleted_at timestamp with time zone,
    CONSTRAINT prefill_groups_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_prefill_groups_deleted_at ON prefill_groups USING btree (deleted_at);

CREATE INDEX idx_prefill_groups_type ON prefill_groups USING btree (type);

CREATE UNIQUE INDEX uk_prefill_name ON prefill_groups USING btree (name) WHERE (deleted_at IS NULL);

CREATE TABLE quota_data (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint NOT NULL,
    username character varying(64) DEFAULT ''::character varying NOT NULL,
    model_name character varying(64) DEFAULT ''::character varying NOT NULL,
    created_at bigint NOT NULL,
    use_group character varying(64) DEFAULT ''::character varying NOT NULL,
    token_id bigint DEFAULT 0 NOT NULL,
    channel_id bigint DEFAULT 0 NOT NULL,
    node_name character varying(64) DEFAULT ''::character varying NOT NULL,
    token_used bigint DEFAULT 0 NOT NULL,
    count bigint DEFAULT 0 NOT NULL,
    quota bigint DEFAULT 0 NOT NULL,
    CONSTRAINT quota_data_pkey PRIMARY KEY (id),
    CONSTRAINT quota_data_dimensions_key UNIQUE (user_id, username, model_name, created_at, use_group, token_id, channel_id, node_name)
);

CREATE INDEX idx_qdt_created_at ON quota_data USING btree (created_at);

CREATE INDEX idx_qdt_model_user_name ON quota_data USING btree (model_name, username);

CREATE INDEX idx_quota_data_channel_id ON quota_data USING btree (channel_id);

CREATE INDEX idx_quota_data_node_name ON quota_data USING btree (node_name);

CREATE INDEX idx_quota_data_token_id ON quota_data USING btree (token_id);

CREATE INDEX idx_quota_data_use_group ON quota_data USING btree (use_group);

CREATE INDEX idx_quota_data_user_id ON quota_data USING btree (user_id);

CREATE TABLE redemptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint,
    key character(32),
    status bigint DEFAULT 1,
    name text,
    quota bigint DEFAULT 100,
    created_time bigint,
    redeemed_time bigint,
    used_user_id bigint,
    deleted_at timestamp with time zone,
    expired_time bigint,
    CONSTRAINT redemptions_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_redemptions_deleted_at ON redemptions USING btree (deleted_at);

CREATE UNIQUE INDEX idx_redemptions_key ON redemptions USING btree (key);

CREATE INDEX idx_redemptions_name ON redemptions USING btree (name);

CREATE TABLE setups (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version character varying(50) NOT NULL,
    initialized_at bigint NOT NULL,
    CONSTRAINT setups_pkey PRIMARY KEY (id)
);

CREATE TABLE subscription_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint,
    plan_id bigint,
    money numeric,
    trade_no character varying(255),
    payment_method character varying(50),
    payment_provider character varying(50) DEFAULT ''::character varying,
    status text,
    create_time bigint,
    complete_time bigint,
    provider_payload text,
    CONSTRAINT subscription_orders_pkey PRIMARY KEY (id),
    CONSTRAINT uni_subscription_orders_trade_no UNIQUE (trade_no)
);

CREATE INDEX idx_subscription_orders_plan_id ON subscription_orders USING btree (plan_id);

CREATE INDEX idx_subscription_orders_trade_no ON subscription_orders USING btree (trade_no);

CREATE INDEX idx_subscription_orders_user_id ON subscription_orders USING btree (user_id);

CREATE TABLE subscription_plans (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title character varying(128) NOT NULL,
    subtitle character varying(255) DEFAULT ''::character varying,
    price_amount numeric(10,6) DEFAULT 0 NOT NULL,
    currency character varying(8) DEFAULT 'USD'::character varying NOT NULL,
    duration_unit character varying(16) DEFAULT 'month'::character varying NOT NULL,
    duration_value bigint DEFAULT 1 NOT NULL,
    custom_seconds bigint DEFAULT 0 NOT NULL,
    enabled boolean DEFAULT true,
    sort_order bigint DEFAULT 0,
    allow_balance_pay boolean,
    allow_wallet_overflow boolean,
    stripe_price_id character varying(128) DEFAULT ''::character varying,
    creem_product_id character varying(128) DEFAULT ''::character varying,
    waffo_pancake_product_id character varying(128) DEFAULT ''::character varying,
    max_purchase_per_user bigint DEFAULT 0,
    upgrade_group character varying(64) DEFAULT ''::character varying,
    downgrade_group character varying(64) DEFAULT ''::character varying,
    total_amount bigint DEFAULT 0 NOT NULL,
    quota_reset_period character varying(16) DEFAULT 'never'::character varying,
    quota_reset_custom_seconds bigint DEFAULT 0,
    created_at bigint,
    updated_at bigint,
    CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);

CREATE TABLE subscription_pre_consume_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_id character varying(64),
    user_id bigint,
    user_subscription_id bigint,
    pre_consumed bigint DEFAULT 0 NOT NULL,
    status character varying(32),
    created_at bigint,
    updated_at bigint,
    CONSTRAINT subscription_pre_consume_records_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_subscription_pre_consume_records_request_id ON subscription_pre_consume_records USING btree (request_id);

CREATE INDEX idx_subscription_pre_consume_records_status ON subscription_pre_consume_records USING btree (status);

CREATE INDEX idx_subscription_pre_consume_records_updated_at ON subscription_pre_consume_records USING btree (updated_at);

CREATE INDEX idx_subscription_pre_consume_records_user_id ON subscription_pre_consume_records USING btree (user_id);

CREATE INDEX idx_subscription_pre_consume_records_user_subscription_id ON subscription_pre_consume_records USING btree (user_subscription_id);



CREATE TABLE system_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_id character varying(64),
    type character varying(64),
    status character varying(32),
    active_key character varying(64),
    payload text,
    state text,
    result text,
    error text,
    locked_by character varying(128),
    created_at bigint,
    updated_at bigint,
    CONSTRAINT system_tasks_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_system_tasks_active_key ON system_tasks USING btree (active_key);

CREATE INDEX idx_system_tasks_created_at ON system_tasks USING btree (created_at);

CREATE INDEX idx_system_tasks_locked_by ON system_tasks USING btree (locked_by);

CREATE INDEX idx_system_tasks_status ON system_tasks USING btree (status);

CREATE UNIQUE INDEX idx_system_tasks_task_id ON system_tasks USING btree (task_id);

CREATE INDEX idx_system_tasks_type ON system_tasks USING btree (type);

CREATE INDEX idx_system_tasks_updated_at ON system_tasks USING btree (updated_at);

CREATE TABLE task_plugins (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    key character varying(128) NOT NULL,
    api_version bigint NOT NULL,
    version character varying(64) NOT NULL,
    source text NOT NULL,
    source_hash character varying(64) NOT NULL,
    enabled boolean NOT NULL,
    active boolean NOT NULL,
    created_at bigint NOT NULL,
    remark text,
    CONSTRAINT task_plugins_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_task_plugins_active ON task_plugins USING btree (active);

CREATE UNIQUE INDEX uk_task_plugin_key_version ON task_plugins USING btree (key, version);

CREATE TABLE tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at bigint,
    updated_at bigint,
    task_id character varying(191),
    platform character varying(30),
    user_id bigint,
    "group" character varying(50),
    channel_id bigint,
    quota bigint,
    billing_pending boolean NOT NULL DEFAULT false,
    billing_action character varying(32) NOT NULL DEFAULT ''::character varying,
    billing_operation_id character varying(128) NOT NULL DEFAULT ''::character varying,
    billing_target_quota bigint NOT NULL DEFAULT 0,
    billing_delta bigint NOT NULL DEFAULT 0,
    billing_audit json,
    action character varying(40),
    status character varying(20),
    fail_reason text,
    submit_time bigint,
    start_time bigint,
    finish_time bigint,
    progress character varying(20),
    properties json,
    private_data json,
    data json,
    CONSTRAINT tasks_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_tasks_action ON tasks USING btree (action);

CREATE INDEX idx_tasks_channel_id ON tasks USING btree (channel_id);

CREATE INDEX idx_tasks_created_at ON tasks USING btree (created_at);

CREATE INDEX idx_tasks_finish_time ON tasks USING btree (finish_time);

CREATE INDEX idx_tasks_platform ON tasks USING btree (platform);

CREATE INDEX idx_tasks_progress ON tasks USING btree (progress);

CREATE INDEX idx_tasks_start_time ON tasks USING btree (start_time);

CREATE INDEX idx_tasks_status ON tasks USING btree (status);

CREATE INDEX idx_tasks_submit_time ON tasks USING btree (submit_time);

CREATE INDEX idx_tasks_task_id ON tasks USING btree (task_id);

CREATE INDEX idx_tasks_user_id ON tasks USING btree (user_id);

CREATE INDEX idx_tasks_billing_pending ON tasks USING btree (billing_pending, id);

ALTER TABLE tasks ADD CONSTRAINT tasks_billing_action_check
    CHECK (billing_action IN ('', 'submission', 'adjustment', 'completion', 'refund', 'unknown'));

CREATE TABLE tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint,
    key character varying(128),
    status bigint DEFAULT 1,
    name text,
    created_time bigint,
    accessed_time bigint,
    expired_time bigint DEFAULT '-1'::integer,
    remain_quota bigint DEFAULT 0,
    unlimited_quota boolean,
    model_limits_enabled boolean,
    model_limits text[] NOT NULL DEFAULT '{}',
    allow_ips text DEFAULT ''::text,
    used_quota bigint DEFAULT 0,
    "group" text DEFAULT ''::text,
    cross_group_retry boolean,
    auto_groups text[],
    deleted_at timestamp with time zone,
    CONSTRAINT tokens_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_tokens_deleted_at ON tokens USING btree (deleted_at);

CREATE UNIQUE INDEX idx_tokens_key ON tokens USING btree (key);

CREATE INDEX idx_tokens_name ON tokens USING btree (name);

CREATE INDEX idx_tokens_user_id ON tokens USING btree (user_id);

CREATE TABLE top_ups (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint,
    amount bigint,
    money numeric,
    trade_no character varying(255),
    payment_method character varying(50),
    payment_provider character varying(50) DEFAULT ''::character varying,
    create_time bigint,
    complete_time bigint,
    status text,
    CONSTRAINT top_ups_pkey PRIMARY KEY (id),
    CONSTRAINT uni_top_ups_trade_no UNIQUE (trade_no)
);

CREATE INDEX idx_top_ups_trade_no ON top_ups USING btree (trade_no);

CREATE INDEX idx_top_ups_user_id ON top_ups USING btree (user_id);

CREATE TABLE two_fa_backup_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint NOT NULL,
    code_hash character varying(255) NOT NULL,
    is_used boolean,
    used_at timestamp with time zone,
    created_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT two_fa_backup_codes_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_two_fa_backup_codes_deleted_at ON two_fa_backup_codes USING btree (deleted_at);

CREATE INDEX idx_two_fa_backup_codes_user_id ON two_fa_backup_codes USING btree (user_id);

CREATE TABLE two_fas (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint NOT NULL,
    secret character varying(255) NOT NULL,
    is_enabled boolean,
    failed_attempts bigint DEFAULT 0,
    locked_until timestamp with time zone,
    last_used_at timestamp with time zone,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT two_fas_pkey PRIMARY KEY (id),
    CONSTRAINT uni_two_fas_user_id UNIQUE (user_id)
);

CREATE INDEX idx_two_fas_deleted_at ON two_fas USING btree (deleted_at);

CREATE INDEX idx_two_fas_user_id ON two_fas USING btree (user_id);

CREATE TABLE user_oauth_bindings (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint NOT NULL,
    provider_id bigint NOT NULL,
    provider_user_id character varying(256) NOT NULL,
    created_at timestamp with time zone,
    CONSTRAINT user_oauth_bindings_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ux_provider_userid ON user_oauth_bindings USING btree (provider_id, provider_user_id);

CREATE UNIQUE INDEX ux_user_provider ON user_oauth_bindings USING btree (user_id, provider_id);

CREATE TABLE user_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint,
    plan_id bigint,
    amount_total bigint DEFAULT 0 NOT NULL,
    amount_used bigint DEFAULT 0 NOT NULL,
    start_time bigint,
    end_time bigint,
    status character varying(32),
    source character varying(32) DEFAULT 'order'::character varying,
    last_reset_time bigint DEFAULT 0,
    next_reset_time bigint DEFAULT 0,
    upgrade_group character varying(64) DEFAULT ''::character varying,
    prev_user_group character varying(64) DEFAULT ''::character varying,
    downgrade_group character varying(64) DEFAULT ''::character varying,
    allow_wallet_overflow boolean,
    created_at bigint,
    updated_at bigint,
    CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_user_sub_active ON user_subscriptions USING btree (user_id, status, end_time);

CREATE INDEX idx_user_subscriptions_end_time ON user_subscriptions USING btree (end_time);

CREATE INDEX idx_user_subscriptions_next_reset_time ON user_subscriptions USING btree (next_reset_time);

CREATE INDEX idx_user_subscriptions_plan_id ON user_subscriptions USING btree (plan_id);

CREATE INDEX idx_user_subscriptions_status ON user_subscriptions USING btree (status);

CREATE INDEX idx_user_subscriptions_user_id ON user_subscriptions USING btree (user_id);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username text,
    password text NOT NULL,
    display_name text,
    role bigint DEFAULT 1,
    status bigint DEFAULT 1,
    email text,
    github_id text,
    discord_id text,
    oidc_id text,
    wechat_id text,
    telegram_id text,
    access_token character varying(32),
    quota bigint DEFAULT 0,
    used_quota bigint DEFAULT 0,
    request_count bigint DEFAULT 0,
    "group" character varying(64) DEFAULT 'default'::character varying,
    aff_code character varying(32),
    aff_count bigint DEFAULT 0,
    aff_quota bigint DEFAULT 0,
    aff_history bigint DEFAULT 0,
    inviter_id bigint,
    deleted_at timestamp with time zone,
    linux_do_id text,
    setting text,
    remark character varying(255),
    stripe_customer character varying(64),
    created_at bigint,
    last_login_at bigint DEFAULT 0,
    auth_version bigint DEFAULT 1 NOT NULL,
    CONSTRAINT uni_users_username UNIQUE (username),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_users_access_token ON users USING btree (access_token);

CREATE UNIQUE INDEX idx_users_aff_code ON users USING btree (aff_code);

CREATE INDEX idx_users_deleted_at ON users USING btree (deleted_at);

CREATE INDEX idx_users_discord_id ON users USING btree (discord_id);

CREATE INDEX idx_users_display_name ON users USING btree (display_name);

CREATE INDEX idx_users_email ON users USING btree (email);

CREATE INDEX idx_users_git_hub_id ON users USING btree (github_id);

CREATE INDEX idx_users_inviter_id ON users USING btree (inviter_id);

CREATE INDEX idx_users_linux_do_id ON users USING btree (linux_do_id);

CREATE INDEX idx_users_oidc_id ON users USING btree (oidc_id);

CREATE INDEX idx_users_stripe_customer ON users USING btree (stripe_customer);

CREATE INDEX idx_users_telegram_id ON users USING btree (telegram_id);

CREATE INDEX idx_users_username ON users USING btree (username);

CREATE INDEX idx_users_we_chat_id ON users USING btree (wechat_id);

CREATE TABLE vendors (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(128) NOT NULL,
    description text,
    icon character varying(128),
    status bigint DEFAULT 1,
    created_time bigint,
    updated_time bigint,
    deleted_at timestamp with time zone,
    CONSTRAINT vendors_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_vendors_deleted_at ON vendors USING btree (deleted_at);

CREATE UNIQUE INDEX uk_vendor_name_delete_at ON vendors USING btree (name) WHERE deleted_at IS NULL;

INSERT INTO options (key, value) VALUES ('theme.frontend', 'default');

CREATE TABLE quota_batch_receipts (
    id uuid PRIMARY KEY,
    applied_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE quota_batch_deliveries (
    id uuid PRIMARY KEY,
    update_type smallint NOT NULL,
    entity_id bigint NOT NULL,
    delta bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT quota_batch_deliveries_update_type_check CHECK (update_type BETWEEN 0 AND 4),
    CONSTRAINT quota_batch_deliveries_entity_id_check CHECK (entity_id > 0),
    CONSTRAINT quota_batch_deliveries_delta_check CHECK (delta <> 0)
);

CREATE INDEX idx_quota_batch_deliveries_created_at
    ON quota_batch_deliveries USING btree (created_at, id);

-- Durable request billing lifecycle. The request id is the operation's
-- idempotency key; token secrets are intentionally absent from this table.
CREATE TABLE billing_sessions (
    request_id character varying(64) PRIMARY KEY,
    user_id bigint NOT NULL,
    token_id bigint NOT NULL,
    source character varying(32) NOT NULL,
    model_name character varying(255) NOT NULL DEFAULT ''::character varying,
    preference character varying(32) NOT NULL DEFAULT ''::character varying,
    requested_quota bigint NOT NULL DEFAULT 0,
    reserved_quota bigint NOT NULL DEFAULT 0,
    actual_quota bigint,
    subscription_id bigint NOT NULL DEFAULT 0,
    plan_id bigint NOT NULL DEFAULT 0,
    plan_title character varying(255) NOT NULL DEFAULT ''::character varying,
    user_quota bigint NOT NULL DEFAULT 0,
    subscription_total bigint NOT NULL DEFAULT 0,
    subscription_used bigint NOT NULL DEFAULT 0,
    subscription_post_delta bigint NOT NULL DEFAULT 0,
    token_unlimited boolean NOT NULL DEFAULT false,
    playground boolean NOT NULL DEFAULT false,
    force_pre_consume boolean NOT NULL DEFAULT false,
    trusted boolean NOT NULL DEFAULT false,
    status character varying(32) NOT NULL,
    channel_id bigint NOT NULL DEFAULT 0,
    usage_recorded boolean NOT NULL DEFAULT false,
    pending_action character varying(32) NOT NULL DEFAULT ''::character varying,
    intent_actual bigint,
    intent_channel bigint NOT NULL DEFAULT 0,
    intent_usage boolean NOT NULL DEFAULT false,
    intent_requires_commit boolean NOT NULL DEFAULT false,
    created_at bigint NOT NULL,
    updated_at bigint NOT NULL,
    CONSTRAINT billing_sessions_quota_check CHECK (
        requested_quota BETWEEN 0 AND 2147483647 AND
        reserved_quota BETWEEN 0 AND 2147483647 AND
        (actual_quota IS NULL OR actual_quota BETWEEN 0 AND 2147483647) AND
        (intent_actual IS NULL OR intent_actual BETWEEN 0 AND 2147483647) AND
        (status <> 'settled' OR actual_quota IS NOT NULL) AND
        (pending_action <> 'settle' OR intent_actual IS NOT NULL)
    ),
    CONSTRAINT billing_sessions_source_check CHECK (source IN ('wallet', 'subscription')),
    CONSTRAINT billing_sessions_status_check CHECK (status IN ('active', 'settled', 'refunded')),
    CONSTRAINT billing_sessions_pending_action_check CHECK (pending_action IN ('', 'settle', 'refund', 'reconcile'))
);

CREATE INDEX idx_billing_sessions_status_updated_at
    ON billing_sessions USING btree (status, updated_at, request_id);

CREATE INDEX idx_billing_sessions_user_id
    ON billing_sessions USING btree (user_id);

CREATE TABLE billing_adjustment_receipts (
    operation_id character varying(128) PRIMARY KEY,
    user_id bigint NOT NULL,
    token_id bigint NOT NULL,
    source character varying(32) NOT NULL,
    subscription_id bigint NOT NULL DEFAULT 0,
    delta bigint NOT NULL,
    usage_delta bigint NOT NULL DEFAULT 0,
    request_delta bigint NOT NULL DEFAULT 0,
    channel_id bigint NOT NULL DEFAULT 0,
    token_unlimited boolean NOT NULL DEFAULT false,
    playground boolean NOT NULL DEFAULT false,
    historical_token boolean NOT NULL DEFAULT false,
    applied_at bigint NOT NULL,
    CONSTRAINT billing_adjustment_receipts_source_check CHECK (source IN ('wallet', 'subscription')),
    CONSTRAINT billing_adjustment_receipts_quota_check CHECK (
        delta BETWEEN -2147483647 AND 2147483647 AND
        usage_delta BETWEEN -2147483647 AND 2147483647 AND
        request_delta BETWEEN -2147483647 AND 2147483647
    )
);

CREATE INDEX idx_billing_adjustment_receipts_user_id
    ON billing_adjustment_receipts USING btree (user_id);

COMMIT;
