-- Initial schema for a fresh PostgreSQL 18+ deployment.

BEGIN;

CREATE TABLE logs (
    event_id character varying(36) DEFAULT '',
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint,
    created_at bigint,
    type bigint,
    content text,
    username text DEFAULT ''::text,
    token_name text DEFAULT ''::text,
    model_name text DEFAULT ''::text,
    quota bigint DEFAULT 0,
    prompt_tokens bigint DEFAULT 0,
    completion_tokens bigint DEFAULT 0,
    use_time bigint DEFAULT 0,
    is_stream boolean,
    channel_id bigint,
    channel_name text,
    token_id bigint DEFAULT 0,
    "group" text,
    ip text DEFAULT ''::text,
    request_id character varying(64) DEFAULT ''::character varying,
    upstream_request_id character varying(128) DEFAULT ''::character varying,
    other text,
    CONSTRAINT logs_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_created_at_id ON logs USING btree (created_at, id);


CREATE INDEX idx_logs_channel_id ON logs USING btree (channel_id);

CREATE INDEX idx_logs_group ON logs USING btree ("group");

CREATE INDEX idx_logs_ip ON logs USING btree (ip);

CREATE INDEX idx_logs_model_name ON logs USING btree (model_name);

CREATE INDEX idx_logs_request_id ON logs USING btree (request_id);

CREATE INDEX idx_logs_token_id ON logs USING btree (token_id);

CREATE INDEX idx_logs_token_name ON logs USING btree (token_name);

CREATE INDEX idx_logs_upstream_request_id ON logs USING btree (upstream_request_id);


CREATE INDEX idx_logs_username ON logs USING btree (username);


CREATE INDEX index_username_model_name ON logs USING btree (model_name, username);

CREATE INDEX idx_logs_user_cursor ON logs (user_id, created_at DESC, id DESC);
CREATE INDEX idx_logs_type_cursor ON logs (type, created_at DESC, id DESC);

COMMIT;
